  name: Create Releases

  on:
    release:
      types: [created]
  jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ ubuntu-latest, macOS-latest, windows-latest ]
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Configure JDK
          uses: actions/setup-java@v1
          with:
            java-version: 18
        - name: Make gradlew executable
          run: chmod +x ./gradlew
        - name: Publish
          run: ./gradlew packageReleaseDistributionForCurrentOS
        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              .*.dmg
              .*.msi
              .*.deb